### ISSUE TITLE
Multiple alliance applies

### ISSUE THREAD

**Issue by ogamespec** [ogamespec/ogame-opensource#121]
if there are 2 or more alliance requests together and you try to accept them, the first one accepts it and the second one doesn't seem to find it and gives an error

by @Quaua

**Comment by ogamespec** [comment]
Looks like this:

![image](https://github.com/ogamespec/ogame-opensource/assets/5828819/dac3a7fb-fd9a-4093-9369-9c9cf40e25fa)

**Comment by ogamespec** [comment]
After the application is accepted or rejected, a MyGoto to the `bewerbungen` (alliance applications) page is made.

**Comment by quaua** [comment]
why im even mentioned?

**Comment by ogamespec** [comment]
> why im even mentioned?

I mentioned you before you even registered on GitHub :)

**Comment by ogamespec** [comment]
Oops, sorry, seems another Quaua :) @Quaua00
