### ISSUE TITLE
Alliance -- transferring founder's rights

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ogamespec/ogame-opensource#14]
Looks like it's not working.

**Comment by ogamespec** [comment]
Уделить особое внимание этой фиче и не наступать на те же грабли, что и разработчики.
Например кейс - игрок подал заявку в альянс, её не приняли, игрок удалился, права альянса передали -- что будет?
И много других мелочей.

**Comment by ogamespec** [comment]
Checked it out, it works.
