### ISSUE TITLE
Сообщения -- Разведданные показывать частично

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ogamespec/ogame-opensource#63]
функция не работает

![image](https://github.com/ogamespec/ogame-opensource/assets/5828819/39d6d4f5-2a85-42a7-ac09-55cf2fc6f599)

**Comment by ogamespec** [comment]
Нужны примеры картинок как это было сделано. У меня не сохранилось HTML для этой фичи.

**Comment by ogamespec** [comment]
```In the message menu you can set that espionage reports are only partially displayed - then they are displayed as single-line messages that lead to the actual espionage report via a pop-up window - which then does not deviate from the form shown below.```

https://www.owiki.de/index.php/Spionagebericht

**Comment by ogamespec** [comment]
Похоже что этот функционал повторяет кнопку общих шпионских докладов из Галактики, доступных альянсу.
![s](https://github.com/ogamespec/ogame-opensource/assets/5828819/8ff73257-a819-4170-81cd-9bdba7c25e5b)

**Comment by ogamespec** [comment]
fixed.
![image](https://github.com/ogamespec/ogame-opensource/assets/5828819/c0fe2cec-7835-4fdb-a9d4-adc6db601a83)
